/**
 * Re-export the Phosphor icons used by Providers + Settings pages. Adding
 * new icons here keeps the renderer's import surface small and consistent.
 */
export {
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowSquareOut,
  Brain,
  CaretDown,
  CaretRight,
  CaretUp,
  Check,
  CheckCircle,
  CircleNotch,
  Cube,
  Eye,
  EyeSlash,
  FilmReel,
  FilmStrip,
  Folder,
  FolderOpen,
  Gear,
  GoogleLogo,
  Image,
  Info,
  MagnifyingGlass,
  Moon,
  OpenAiLogo,
  Play,
  Plug,
  Plus,
  SquaresFour,
  Star,
  Sun,
  TiktokLogo,
  Trash,
  VideoCamera,
  WarningCircle,
  X,
  XCircle,
  XLogo,
} from "@phosphor-icons/react";
