/**
 * Re-export the Phosphor icons used by Providers + Settings pages. Adding
 * new icons here keeps the renderer's import surface small and consistent.
 */
export {
  Check,
  CheckCircle,
  CaretDown,
  CaretUp,
  CaretRight,
  XCircle,
  WarningCircle,
  Eye,
  EyeSlash,
  Sun,
  Moon,
  Plug,
  Gear,
  Folder,
  FolderOpen,
  ArrowSquareOut,
  Trash,
  ArrowClockwise,
  CircleNotch,
  Info,
  Plus,
  X,
  Image,
  FilmReel,
  FilmStrip,
  VideoCamera,
  SquaresFour,
  Cube,
  Play,
  MagnifyingGlass,
  ArrowCounterClockwise,
} from "@phosphor-icons/react";
